apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-backend
  template:
    metadata:
      labels:
        app: bitcoin-backend
    spec:
      containers:
        - name: backend
          image: manishmd21/bitcoin-backend:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-frontend
  template:
    metadata:
      labels:
        app: bitcoin-frontend
    spec:
      containers:
        - name: frontend
          image: manishmd21/bitcoin-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-backend
spec:
  selector:
    app: bitcoin-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-frontend
spec:
  selector:
    app: bitcoin-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
