name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Test Backend
        working-directory: bitcoin-price
        run: ./mvnw clean verify
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        working-directory: bitcoin-price
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bitcoin-backend:latest .
      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: bitcoin-price
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bitcoin-backend:latest

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bitcoin-frontend:latest .
      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bitcoin-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Deploy to Kubernetes or Hosting
        run: |
          # Add your deployment commands here
          echo "Deploying..."
