jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image for Backend
        run: docker build -t backend-image -f bitcoin-price/Dockerfile .

      - name: Build Docker Image for Frontend
        run: docker build -t frontend-image -f frontend/Dockerfile .
